### ISSUE TITLE
uninitialized constant ActiveAdmin::Inputs::FilterSelect2MultipleInput::FilterBase

### ISSUE THREAD

**Issue by deafboy2k9** [mfairburn/activeadmin-select2#4]
Hi,

I've tried adding this gem to my Rails app but it seems to be breaking somewhere. It's a pity because it was a really simple gem to use previously.

Here's the output Passenger is giving me when I restart after installing the gem:

uninitialized constant ActiveAdmin::Inputs::FilterSelect2MultipleInput::FilterBase (NameError)
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/bundler/gems/activeadmin-select2-e2c2bd12cd4e/lib/activeadmin/inputs/filter_select2_multiple_input.rb:5:in `<class:FilterSelect2MultipleInput>'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/bundler/gems/activeadmin-select2-e2c2bd12cd4e/lib/activeadmin/inputs/filter_select2_multiple_input.rb:3:in `<module:Inputs>'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/bundler/gems/activeadmin-select2-e2c2bd12cd4e/lib/activeadmin/inputs/filter_select2_multiple_input.rb:2:in `<module:ActiveAdmin>'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/bundler/gems/activeadmin-select2-e2c2bd12cd4e/lib/activeadmin/inputs/filter_select2_multiple_input.rb:1:in `<top (required)>'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/bundler/gems/activeadmin-select2-e2c2bd12cd4e/lib/activeadmin/select2.rb:3:in `<top (required)>'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/bundler/gems/activeadmin-select2-e2c2bd12cd4e/lib/activeadmin-select2.rb:1:in `<top (required)>'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.7/lib/bundler/runtime.rb:76:in `require'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.7/lib/bundler/runtime.rb:72:in `each'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.7/lib/bundler/runtime.rb:72:in `block in require'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.7/lib/bundler/runtime.rb:61:in `each'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.7/lib/bundler/runtime.rb:61:in `require'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.7/lib/bundler.rb:133:in `require'
  /Users/iamlamb/RubymineProjects/Simply Lee/config/application.rb:7:in `<top (required)>'
  /Users/iamlamb/RubymineProjects/Simply Lee/config/environment.rb:2:in `require'
  /Users/iamlamb/RubymineProjects/Simply Lee/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5@global/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  /Users/iamlamb/.rvm/gems/ruby-2.1.5@global/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/Cellar/passenger/4.0.53/libexec/helper-scripts/rack-preloader.rb:112:in `eval'
  /usr/local/Cellar/passenger/4.0.53/libexec/helper-scripts/rack-preloader.rb:112:in `preload_app'
  /usr/local/Cellar/passenger/4.0.53/libexec/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /usr/local/Cellar/passenger/4.0.53/libexec/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/local/Cellar/passenger/4.0.53/libexec/helper-scripts/rack-preloader.rb:28:in `<main>'

Thanks in advance

**Comment by alexvodovoz** [comment]
+1

**Comment by serradura** [comment]
+1

**Comment by pencilcheck** [comment]
+1, please merge
