### ISSUE TITLE
Multi_select filter not working in AA 1.0.0.pre1

### ISSUE THREAD

**Issue by jamesrward** [mfairburn/activeadmin-select2#9]
Using ActiveAdmin 1.0.0.pre1 and everything was working fine until I tried to add some multiple select filters.  I'm filtering records based on country codes in the form of 2 letter alpha codes via the Countries gem.  If I declare my filter as follows:
```ruby
  filter :country, as: :select, collection: Country.all
```
It produces the following source snippet and the filter works as expected a single country:
```html
<div class="filter_form_field filter_select">
<label for="q_country" class="label">Country</label>
<select class="select2-input" id="q_country" name="q[country_in]">
<option value="AD">Andorra</option>
```
With a URI produced as follows:
```
http://localhost:3000/admin/mymodel?utf8=%E2%9C%93&q%5Bcountry_in%5D=CA&commit=Filter&order=id_desc
```

However if I try to get it working with multiple select via the following
```ruby
  filter :country, as: :select2_multiple, collection: Country.all
```
I end up with an oddly formatted list item in the filter panel and the following source snippet:
```html
<li class="select2_multiple input required" id="q_country_input">
<label for="q_country" class="label">Country<abbr title="required">*</abbr></label>
<input name="q[country][]" type="hidden" value="" />
<select class="select2-input" multiple="multiple" id="q_country" name="q[country][]">
<option value=""></option>
<option value="AD">Andorra</option>
```
The filter does not work at all even for single value selections and I end up with URIs like the following:
```
http://localhost:3000/admin/mymodel?utf8=%E2%9C%93&q%5Bcountry%5D%5B%5D=CA&commit=Filter&order=id_desc
```

Any idea  what is causing the huge difference between select2_multiple and the default select2 behaviour?  I am using select2_multiple in my forms and it works fine.

**Comment by jamesrward** [comment]
Trying to solve my own problem and it looks like this fork should have solved these issues:
https://github.com/atroppmann/activeadmin-select2/tree/activeadmin-1.0.0

But when I search through the gem it looks like these changes are already incorporated.
I tried changing my gemfile to the following and reinstalled all the gems but it does not appear to make any difference: 
```ruby
gem 'activeadmin-select2', github: 'atroppmann/activeadmin-select2', branch: 'activeadmin-1.0.0'
```

**Comment by jostster** [comment]
Having the same issue. It seems that even selecting an option when using :select2_multiple as a filter doesn't work.

**Comment by adisos** [comment]
+1

**Comment by jostster** [comment]
Seems like the project is no longer active. not sure how to get this fixed. Right now multiple select doesn't work at all.

**Comment by mfairburn** [comment]
So sorry for not dealing with this; flooded with work :(

It appears to be working fine on Pre2 so closing this; please re-open if still having issues

**Comment by swedishpotato** [comment]
Hi 

I'm using AA pre4 but get the following problem:

    filter :countries, as: :select, collection: proc { Country.all }, label: "Implementation Country"

works fine!

    filter :countries, as: :select2_multiple, collection: proc { Country.all }, label: "Implementation Country"

says, "undefined method `countries' for #<Ransack::Search:0x007fc4155967b8>"

Any idea why @mfairburn? Help much appreciated!
